FROM eclipse-temurin:21-jre

WORKDIR /app

# curl нужен, чтобы скачать jar
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

# entrypoint-скрипт
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 8080

ENTRYPOINT ["/entrypoint.sh"]
